FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY station_publisher.py ./
COPY utils/ ./utils/
COPY .env ./

CMD ["python", "station_publisher.py"]
